### ISSUE TITLE
Translation To Turkish

### ISSUE THREAD

**Issue by umutphp** [foo123/code-optimization-methods#1]
Do you mind if I translate the article into Turkish?

**Comment by foo123** [comment]
Not at all! After all this was written in the hope that it will be useful.
If it is useful then I am happy no matter which language.
Cheers from Greece!

**Comment by umutphp** [comment]
ευχαριστώ πολύ :))

I have two options for doing the translation;

Option #1: Your repo with a separate MD file for Turkish (tr.md)
Option #2: Forked repo for the Turkish translation

Which one do you prefer to have?

Cheers from Turkey!

**Comment by foo123** [comment]
I would go for the 1st option, I think it is more flexible (eg to update in the future and so on). But I really dont mind so much, use whatever suits you.

**Comment by foo123** [comment]
Do note that I update this article whenever I find new tricks or information. So take this into account and see what suits you best if you want to keep up with the translation

**Comment by umutphp** [comment]
For option 1, I can also propose you a tool which I have experienced when I involved in translation of another repo like yours. The tool is [GitLocalize](https://gitlocalize.com/). It notices the translation owner when the master content is updated.

**Comment by foo123** [comment]
I did take a look at the tool, but I dont want to give full access to all my repositories to the tool (esp private ones). I dont see an option to grant access to only a specific repo.
If you have another alternative then you can share it. Else I will have to think about the tool.

**Comment by umutphp** [comment]
Ok then :). Let me start doing translation on my fork.

**Comment by foo123** [comment]
Ok no problem :)

**Comment by foo123** [comment]
Merged your translation and added it under a new section **Translations** with a reference to the contributor (you).

Cheers

**Comment by umutphp** [comment]
Many thanx for such a great article.
